### ISSUE TITLE
Country restrictions in Google Play Store

### ISSUE THREAD

**Issue by hmert** [googlecreativelab/Sprayscape#1]
why do you make country restrictions in this app?

**Comment by ryburke** [comment]
Thanks for your interest! We are actively working on expanding our country coverage. More updates soon.

**Comment by hmert** [comment]
thank you, please always add Turkey🇹🇷

**Comment by HalfdanJ** [comment]
Sprayscape is now available globally 🌍

**Comment by hmert** [comment]
👏
